### PR TITLE
Add note suggesting FDP covers main spending line categorizations...

### LINKED ISSUE #142: 'Funds source' classification
Most Argentine budgets use a *Fuente de Financiamiento* classification, in addition to the usual administrative, economic and functional.

I'm wondering if it would make sense to include it in the spec, and how common is that in other budgets.

For an example, see: http://bahia.presupuestoabierto.org/dataset_ejecucion_gastos_bahia_user_bahia?chart=barchart&dimension=Fuente%20de%20Financiamiento&measures=Aprobado

### PR DESCRIPTION
**Pull request by danfowler**
…but there may be phases, directions, and classifications that can’t be
directly modeled using the standard.

Closes #142

### CODE REVIEW

**Comment by rgrp** [comment]
Personally I'm something of a wontfix on #142 and on this PR. The reason is I'm not sure there is much to say - what we have in the PR is nicely worded but somewhat "contentless" as we are basically just saying that "sometimes, though we're not sure when, you won't be able to model your data with this spec". I am not sure this adds much and if anything is a slight negative in that we have more to read and vaguely worded caveat that may raise concerns without addressing them.

**Comment by danfowler** [comment]
I get it.  I'm OK with closing as a WONTFIX.

**Comment by jazzido** [comment]
…that said, that note might help clarify that the classifications are not mandatory. Without that note, a user could interpret that FDP is not sufficient to model a *funds source* classification.

**Comment by rgrp** [comment]
@jazzido good point but my sense is that we may want that in the "primer" / tutorial rather than the core spec. The suggested text for me was not really clear: did this mean you could or could not support this in the spec. In truth the spec allows for substantial flexibility and I think the best way to demonstrate that is probably in examples and tutorials.

**Comment by danfowler** [comment]
@rgrp @jazzido perhaps we should create an issue to develop such a primer or tutorial?

**Comment by rgrp** [comment]
@danfowler ++1

**Pull request closed without merging**
