### PR TITLE
Remove quality levels 0.3.0-alpha10

### LINKED ISSUE #95: Make "quality levels" more explicit
Currently, there is a concept of Fiscal Data Package having "quality" levels.

> We also emphasize that what we provide is a framework rather than a strict standard. That is, we provide recommendations on what information should be provided rather than strict requirements. These recommendations are also categorised into “quality” levels. Each level requires more information be provided.

However, the spec could lay out a more explicit definition of how these quality levels (and parenthetical quality levels) are actually generated from the information provided in the data package.  It might also be helpful to describe how the "quality" level can actually be used by an implementation.

See: https://github.com/openspending/fiscal-data-package/commit/bc3ac9fc0685837414573c9e0efccc8966dabe15#commitcomment-14468305

### PR DESCRIPTION
**Pull request by danfowler**
Closes #95

### CODE REVIEW

**Comment by danfowler** [comment]
@rgrp can you review?  relevant commit: https://github.com/openspending/fiscal-data-package/commit/d3f0465cad88d6603e678b3d887965181c4d2435

**Comment by rgrp** [comment]
This seems good to go but obviously includes other changes so is pending on them :-)

**Comment by danfowler** [comment]
@rgrp I should've done this one first! :sweat: :smile:

**Comment by rgrp** [comment]
Could we redo pull requests to get his in first without dependency on other ones and we then merge this.

**Comment by danfowler** [comment]
@rgrp https://github.com/openspending/fiscal-data-package/pull/130

**Comment by danfowler** [comment]
Closing in favor of #130.

**Pull request closed without merging**
