### PR TITLE
Remove fact as dimension type 0.3.0-alpha8

### PR DESCRIPTION
**Pull request by danfowler**
As suggested in #110

### CODE REVIEW

**Comment by pwalsh** [comment]
+1

**Comment by danfowler** [comment]
@rgrp can you review after https://github.com/openspending/fiscal-data-package/pull/120

Rebased with source-to-field PR, relevant commit here: https://github.com/openspending/fiscal-data-package/commit/d825bd707c74018dab262e478863f1e2b3396d9b

**Comment by rgrp** [comment]
Now that I am seeing this I realise more clearly that we did use `fact`. I'm not sure the switch to `other` improves things. Should we remove the attributes that reference `fact` / `other`? Where would we handle an overall identifier for spending items if it were present? (Does this happen much?).

/cc @pwalsh

**Comment by pwalsh** [comment]
Note sure what else I can add that I haven't already said here: https://github.com/openspending/fiscal-data-package/issues/110

Would love to see some real world examples where we'd use a `fact` dimension.

**Comment by danfowler** [comment]
The case for budget line items IDs: comparability [slide 18](https://www.fiscal.treasury.gov/fstraining/events/Session3_1%20Anders%20Pedersen_Federal%20Treasury-Budget_%20Data_Package_Townhall.pdf)

My thoughts:

- a quick spot check of the original CSVs uploaded to the original OpenSpending tells me that it is rare for a budget item to have a unique id associated with it.
- "fact" is probably the wrong name for a dimension with these attributes at any rate
- if we do have this in the spec, perhaps we should be a bit more prescriptive about what we expect this ID to look like (examples where two different datasets use the same ID for a budget item?)

@rgrp I think you're right that giving these items an `other` type is probably not helpful, so I can remove them altogether.  I don't think we can support this unique-id-per-budget-item in the spec until 1) we have a good example of a use case and 2) we have worked out exactly how an implementer would use and generate IDs

**Comment by pwalsh** [comment]
Dan, the unique ID thing is only tangentially related to a fact dimension. I really think we should address that as its own issue here: https://github.com/openspending/fiscal-data-package/issues/109

**Comment by rgrp** [comment]
Closing as we will resubmit in new PR.

**Pull request closed without merging**
