### PR TITLE
[m] Add support for data package profiles per #82

### PR DESCRIPTION
**Pull request by danfowler**
I’m assuming that the `base` profile is assumed.

### CODE REVIEW

**Comment by danfowler** [comment]
Moved: https://github.com/openspending/fiscal-data-package/commit/5e3fa092b9e0c61eb05dba68aacdf88bb03af6cb

**Comment by danfowler** [comment]
@rgrp re: removing the diagram stuff, I have a preference for removing commented lines in code under source control.  I can re-add so we don't forget about it.

**Comment by rgrp** [comment]
@danfowler my apologies I think i may have merged other PR first. Can you rebase and then we get this in. Let's not worry about the diagram as you say.

**Comment by danfowler** [comment]
@rgrp no worries, merging

**Pull request merged**
